version: "3.7"

services:
    # image project
    app:
        container_name: course-platform-laravel
        build:
            context: .
            dockerfile: Dockerfile
        image: igorwebs/laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - laravel
    
    # nginx
    nginx:
        container_name: course-platform-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "80:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel

    # db mysql
    mysql:
        container_name: course-platform-mysql
        image: mysql:5.7.22
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes: 
            - mysqldbvolume-course-platform:/var/lib/mysql
        ports: 
            - "3306:3306"
        networks: 
            - laravel

    # queue
    queue:
        container_name: course-platform-queue
        image: igorwebs/laravel-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./:/var/www
        depends_on: 
            - redis
            - app
        networks: 
            - laravel

    # redis
    redis:
        container_name: course-platform-redis
        image: redis:latest
        networks: 
            - laravel

networks: 
    laravel:
        driver: bridge

# Volume
volumes:
  mysqldbvolume-course-platform:
    driver: local